[build]
  command = "npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/api/*"
  to = "https://linklazarus-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200